### ISSUE TITLE
Regarding keeping development private

### ISSUE THREAD

**Issue by mkschreder** [MAVProxyUser/NoTauLabsNag#23]
While I do consider the changes to copyright after forking off to taualabs to be a total dick move on their part, it is also worth noting that keeping subsequent changes private is perfectly alright for GPL code. If they own the code they can do that (although it would be surprising if they owned all of it). And also they are not obligated to put new features on github right away either. It is only required if a third party makes modifications and then distributes their changes. What I do not like about current state of openpilot/librepilot/taulabs is that the privatisation of code is being done in a sneaky fashion instead of just openly stating that they only release latest versions in binary form and later push their changes to the community. In fact, I would be glad if they did it like that and would keep everything new private for a time so they can make money because they have been doing it all wrong and then complaining that they can not make any money while working 12h per day. Follow the example of ID software when it was at it's best: release a top notch commercial product and when it has done it's work at supporting the project financially release it as open source to inspire modifications. I think openpilot has great potential. It is very sad that the team has split apart.

**Comment by MAVProxyUser** [comment]
"It is only required if a third party makes modifications and then distributes their changes." 

They DID make changes... published to GooglePlay (added a nag screen) and did not share the changes. 

OpenPilot was dragged out back and shot... it does not exist any more.

**Comment by m-thread** [comment]
I can only speak for LibrePilot here and we do not hide ANY code other than the current changes people might have on their local machines between pushes. We push ALL code to our repos on Bitbucket.

**Comment by m-thread** [comment]
And to quote MAVProxyUser. From what I know OpenPilot is no more.

**Comment by MAVProxyUser** [comment]
YUP I have no issue with Libre "hiding" code... no reports on my end. This repo was and always about James Cotton being a prick... nothing more, nothing less. Hat tip m-thread.

**Comment by mkschreder** [comment]
They may have tried to shoot it but they can not kill it.

"No matter how bad the authority, no matter how much they try to privatize
and capture the community's work, if it's GPL licensed, that work can walk
away and find a better authority."

They have given us pcb designs and source code under GPL. It means that
anyone can take that code and continue working with it, create products
with it and sell them. Of cource anything "based" on the GPL work needs to
be released in source form to all customers, but there is nothing stopping
anyone from continuing the work on openpilot. It is important that everyone
understands that they can freely take openpilot code and make it into
something new. Even make proprietary hardware for it if they want. Unless
OpenPilot is a registered trademark there is even nothing legal stopping
anyone from continuing the work on both the software and the hardware under
the same name. The worst thing that openpilot team did was shutting the
door on the community, instead of understanding that the community can take
care of itself and explicitly granting the community the right to continue
the work (even if it is already granted by the GPL). I hope that the
platform continues to evolve through anyone who feels that they can take
over and continue the development. Maybe it will be LibrePilot from now
on.. maybe something even better.

**Comment by MAVProxyUser** [comment]
You all can try to necessitate the CODE as much as you want... those of us that made up "THE PROJECT" are gone... moved on to other things. You aren't going to bring the band back together. 

"OpenPilot" and OpenPilot the entity / the group of friends, etc are not the same thing. What was... isn't. What was... won't ever be. Go find a new community. 

No one here is preaching anti GPL stuff... OPENPILOT IS DEAD... pick at the bones if you wish.

**Comment by MAVProxyUser** [comment]
"he worst thing that openpilot team did was shutting the
door on the community"... go on with that nonsense. The community shut the door on *US* long ago. Politics deeply rooted in "community" tear fun things apart.

**Comment by m-thread** [comment]
For the record. 
LibrePilot was founded as a result of the majority of the core project members dissatisfaction with the route the OpenPilot project was about to take. There was an lively and animated discussion in the core of the team on the 'the cathedral and the bazaar' theme and this resulted in the beginning of the end of OpenPilot. LibrePilot is all for open and unlimited development (bazaar style) focused on collaboration and exchange with other projects.
The OpenPilot project is dead, but its legacy will live on for a long time and in many forms.

**Comment by MAVProxyUser** [comment]
https://www.youtube.com/watch?v=-F-3E8pyjFo

**Comment by MAVProxyUser** [comment]
https://www.youtube.com/watch?v=q-7l8cnpI4k

**Comment by mikecarr** [comment]
I do miss the old days of OpenPilot when people got along and got things done, I think OpenPilot hardware and software will live on, probably in the form of LibrePilot or others writing code for OP (F4) hardware (i.e. RaceFlight).
